--*********************************************************************************

--*********************************************************************************
--

-- (c) Countersoft Gemini

--

-- DATA MIGRATION SCRIPT to Gemini 7.5.0

---

--*********************************************************************************

--*********************************************************************************

DELETE FROM gemini_install WHERE attribute_key = N'VERSION'
INSERT INTO gemini_install (attribute_key,attribute_value) VALUES (N'VERSION',N'7.5.0')

TRUNCATE TABLE gemini_systemlog

ALTER TABLE gemini_issues ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_chat ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_alerttemplates ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_rulesactions ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_types ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_sourcecontrolissuefiles ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_adgroups ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_globalsecurityschemeroles ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_admappings ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projecttemplate ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuelinks ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_appointments ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issueattachments ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_affectedversions ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issueviewings ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_watchissues ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuestatus ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectgroups ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_systemlocks ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectversionattributevalues ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectversionattributes ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuelinktypes ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issueseverity ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuewidgetdata ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_globalconfigurationwidgetdata ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_cases ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_customfielddefinitions ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_reportpermission ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_userwidgetdata ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_calendar ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_codecommits ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issueaudit ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_timerapps ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_timetracking ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_languages ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuevotes ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_translationcontent ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_userissuesviews ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issueresolutions ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuecomments ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_run_steps ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_run_cases ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_plannerviews ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_plans ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectissuesequence ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_users ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_cardissuesequence ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectattributes ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_run_times ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_history ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuepriorities ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectgroupmembership ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_plan_cases ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issueresources ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_customdata ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_apppermissions ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_webnode ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectaudit ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_webnodedata ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectdocuments ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectdefaultvalues ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_sla ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuecomponents ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_navigationcard ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_customfielddata ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_case_steps ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_install ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_runs ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projectlabels ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_applicationsettings ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_organization ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_organizationmembership ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_attachments ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_testing_case_issues ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_sharedviews ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_optoutemails ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuetimetype ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_versions ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_issuetypes ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_globalsecurityschemes ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_templatedcontent ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_projects ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_components ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
ALTER TABLE gemini_versionmilestone ADD sysstarttime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT '2004-08-01',    sysendtime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),  PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issues  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issues SET sysstarttime = revised
GO
ALTER TABLE gemini_issues ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_chat  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_chat SET sysstarttime = created
GO
ALTER TABLE gemini_chat ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_alerttemplates  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_alerttemplates SET sysstarttime = created
GO
ALTER TABLE gemini_alerttemplates ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_rulesactions  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_rulesactions SET sysstarttime = revised
GO
ALTER TABLE gemini_rulesactions ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_adgroups  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_adgroups SET sysstarttime = created
GO
ALTER TABLE gemini_adgroups ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_globalsecurityschemeroles  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_globalsecurityschemeroles SET sysstarttime = created
GO
ALTER TABLE gemini_globalsecurityschemeroles ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_admappings  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_admappings SET sysstarttime = created
GO
ALTER TABLE gemini_admappings ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projecttemplate  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projecttemplate SET sysstarttime = created
GO
ALTER TABLE gemini_projecttemplate ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issuelinks  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issuelinks SET sysstarttime = created
GO
ALTER TABLE gemini_issuelinks ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_appointments  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_appointments SET sysstarttime = created
GO
ALTER TABLE gemini_appointments ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issueattachments  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issueattachments SET sysstarttime = created
GO
ALTER TABLE gemini_issueattachments ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_affectedversions  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_affectedversions SET sysstarttime = created
GO
ALTER TABLE gemini_affectedversions ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_watchissues  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_watchissues SET sysstarttime = created
GO
ALTER TABLE gemini_watchissues ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projectgroups  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projectgroups SET sysstarttime = created
GO
ALTER TABLE gemini_projectgroups ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_systemlocks  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_systemlocks SET sysstarttime = created
GO
ALTER TABLE gemini_systemlocks ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issuelinktypes  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issuelinktypes SET sysstarttime = created
GO
ALTER TABLE gemini_issuelinktypes ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issuewidgetdata  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issuewidgetdata SET sysstarttime = created
GO
ALTER TABLE gemini_issuewidgetdata ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_globalconfigurationwidgetdata  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_globalconfigurationwidgetdata SET sysstarttime = created
GO
ALTER TABLE gemini_globalconfigurationwidgetdata ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_cases  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_cases SET sysstarttime = revised
GO
ALTER TABLE gemini_testing_cases ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_customfielddefinitions  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_customfielddefinitions SET sysstarttime = created
GO
ALTER TABLE gemini_customfielddefinitions ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_reportpermission  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_reportpermission SET sysstarttime = created
GO
ALTER TABLE gemini_reportpermission ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_userwidgetdata  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_userwidgetdata SET sysstarttime = created
GO
ALTER TABLE gemini_userwidgetdata ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_calendar  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_calendar SET sysstarttime = revised
GO
ALTER TABLE gemini_calendar ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_codecommits  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_codecommits SET sysstarttime = created
GO
ALTER TABLE gemini_codecommits ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issueaudit  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issueaudit SET sysstarttime = created
GO
ALTER TABLE gemini_issueaudit ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_timerapps  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_timerapps SET sysstarttime = created
GO
ALTER TABLE gemini_timerapps ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_timetracking  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_timetracking SET sysstarttime = created
GO
ALTER TABLE gemini_timetracking ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issuevotes  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issuevotes SET sysstarttime = created
GO
ALTER TABLE gemini_issuevotes ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_translationcontent  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_translationcontent SET sysstarttime = revised
GO
ALTER TABLE gemini_translationcontent ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issuecomments  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issuecomments SET sysstarttime = created
GO
ALTER TABLE gemini_issuecomments ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_run_steps  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_run_steps SET sysstarttime = created
GO
ALTER TABLE gemini_testing_run_steps ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_run_cases  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_run_cases SET sysstarttime = created
GO
ALTER TABLE gemini_testing_run_cases ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_plannerviews  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_plannerviews SET sysstarttime = created
GO
ALTER TABLE gemini_plannerviews ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_plans  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_plans SET sysstarttime = revised
GO
ALTER TABLE gemini_testing_plans ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projectissuesequence  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projectissuesequence SET sysstarttime = created
GO
ALTER TABLE gemini_projectissuesequence ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_users  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_users SET sysstarttime = created
GO
ALTER TABLE gemini_users ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_cardissuesequence  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_cardissuesequence SET sysstarttime = created
GO
ALTER TABLE gemini_cardissuesequence ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_run_times  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_run_times SET sysstarttime = created
GO
ALTER TABLE gemini_testing_run_times ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_history  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_history SET sysstarttime = created
GO
ALTER TABLE gemini_testing_history ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projectgroupmembership  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projectgroupmembership SET sysstarttime = created
GO
ALTER TABLE gemini_projectgroupmembership ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_plan_cases  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_plan_cases SET sysstarttime = revised
GO
ALTER TABLE gemini_testing_plan_cases ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issueresources  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issueresources SET sysstarttime = created
GO
ALTER TABLE gemini_issueresources ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_customdata  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_customdata SET sysstarttime = created
GO
ALTER TABLE gemini_testing_customdata ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_apppermissions  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_apppermissions SET sysstarttime = created
GO
ALTER TABLE gemini_apppermissions ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_webnode  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_webnode SET sysstarttime = created
GO
ALTER TABLE gemini_webnode ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projectaudit  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projectaudit SET sysstarttime = created
GO
ALTER TABLE gemini_projectaudit ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_webnodedata  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_webnodedata SET sysstarttime = created
GO
ALTER TABLE gemini_webnodedata ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projectdocuments  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projectdocuments SET sysstarttime = created
GO
ALTER TABLE gemini_projectdocuments ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projectdefaultvalues  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projectdefaultvalues SET sysstarttime = created
GO
ALTER TABLE gemini_projectdefaultvalues ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_sla  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_sla SET sysstarttime = created
GO
ALTER TABLE gemini_sla ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issuecomponents  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issuecomponents SET sysstarttime = created
GO
ALTER TABLE gemini_issuecomponents ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_navigationcard  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_navigationcard SET sysstarttime = created
GO
ALTER TABLE gemini_navigationcard ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_customfielddata  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_customfielddata SET sysstarttime = revised
GO
ALTER TABLE gemini_customfielddata ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_case_steps  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_case_steps SET sysstarttime = revised
GO
ALTER TABLE gemini_testing_case_steps ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_install  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_install SET sysstarttime = created
GO
ALTER TABLE gemini_install ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_runs  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_runs SET sysstarttime = revised
GO
ALTER TABLE gemini_testing_runs ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projectlabels  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projectlabels SET sysstarttime = created
GO
ALTER TABLE gemini_projectlabels ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_organization  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_organization SET sysstarttime = created
GO
ALTER TABLE gemini_organization ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_organizationmembership  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_organizationmembership SET sysstarttime = created
GO
ALTER TABLE gemini_organizationmembership ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_attachments  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_attachments SET sysstarttime = created
GO
ALTER TABLE gemini_testing_attachments ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_testing_case_issues  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_testing_case_issues SET sysstarttime = created
GO
ALTER TABLE gemini_testing_case_issues ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_sharedviews  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_sharedviews SET sysstarttime = created
GO
ALTER TABLE gemini_sharedviews ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_issuetimetype  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_issuetimetype SET sysstarttime = created
GO
ALTER TABLE gemini_issuetimetype ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_versions  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_versions SET sysstarttime = created
GO
ALTER TABLE gemini_versions ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_globalsecurityschemes  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_globalsecurityschemes SET sysstarttime = created
GO
ALTER TABLE gemini_globalsecurityschemes ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_templatedcontent  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_templatedcontent SET sysstarttime = revised
GO
ALTER TABLE gemini_templatedcontent ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_projects  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_projects SET sysstarttime = created
GO
ALTER TABLE gemini_projects ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_components  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_components SET sysstarttime = created
GO
ALTER TABLE gemini_components ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO
ALTER TABLE gemini_versionmilestone  DROP PERIOD FOR SYSTEM_TIME
GO
UPDATE gemini_versionmilestone SET sysstarttime = created
GO
ALTER TABLE gemini_versionmilestone ADD PERIOD FOR SYSTEM_TIME (sysstarttime, sysendtime)
GO

ALTER TABLE gemini_issues SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issues_history));
ALTER TABLE gemini_chat SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_chat_history));
ALTER TABLE gemini_alerttemplates SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_alerttemplates_history));
ALTER TABLE gemini_rulesactions SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_rulesactions_history));
ALTER TABLE gemini_testing_types SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_types_history));
ALTER TABLE gemini_sourcecontrolissuefiles SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_sourcecontrolissuefiles_history));
ALTER TABLE gemini_adgroups SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_adgroups_history));
ALTER TABLE gemini_globalsecurityschemeroles SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_globalsecurityschemeroles_history));
ALTER TABLE gemini_admappings SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_admappings_history));
ALTER TABLE gemini_projecttemplate SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projecttemplate_history));
ALTER TABLE gemini_issuelinks SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuelinks_history));
ALTER TABLE gemini_appointments SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_appointments_history));
ALTER TABLE gemini_issueattachments SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issueattachments_history));
ALTER TABLE gemini_affectedversions SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_affectedversions_history));
ALTER TABLE gemini_issueviewings SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issueviewings_history));
ALTER TABLE gemini_watchissues SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_watchissues_history));
ALTER TABLE gemini_issuestatus SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuestatus_history));
ALTER TABLE gemini_projectgroups SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectgroups_history));
ALTER TABLE gemini_systemlocks SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_systemlocks_history));
ALTER TABLE gemini_projectversionattributevalues SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectversionattributevalues_history));
ALTER TABLE gemini_projectversionattributes SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectversionattributes_history));
ALTER TABLE gemini_issuelinktypes SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuelinktypes_history));
ALTER TABLE gemini_issueseverity SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issueseverity_history));
ALTER TABLE gemini_issuewidgetdata SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuewidgetdata_history));
ALTER TABLE gemini_globalconfigurationwidgetdata SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_globalconfigurationwidgetdata_history));
ALTER TABLE gemini_testing_cases SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_cases_history));
ALTER TABLE gemini_customfielddefinitions SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_customfielddefinitions_history));
ALTER TABLE gemini_reportpermission SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_reportpermission_history));
ALTER TABLE gemini_userwidgetdata SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_userwidgetdata_history));
ALTER TABLE gemini_calendar SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_calendar_history));
ALTER TABLE gemini_codecommits SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_codecommits_history));
ALTER TABLE gemini_issueaudit SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issueaudit_history));
ALTER TABLE gemini_timerapps SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_timerapps_history));
ALTER TABLE gemini_timetracking SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_timetracking_history));
ALTER TABLE gemini_languages SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_languages_history));
ALTER TABLE gemini_issuevotes SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuevotes_history));
ALTER TABLE gemini_translationcontent SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_translationcontent_history));
ALTER TABLE gemini_userissuesviews SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_userissuesviews_history));
ALTER TABLE gemini_issueresolutions SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issueresolutions_history));
ALTER TABLE gemini_issuecomments SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuecomments_history));
ALTER TABLE gemini_testing_run_steps SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_run_steps_history));
ALTER TABLE gemini_testing_run_cases SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_run_cases_history));
ALTER TABLE gemini_plannerviews SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_plannerviews_history));
ALTER TABLE gemini_testing_plans SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_plans_history));
ALTER TABLE gemini_projectissuesequence SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectissuesequence_history));
ALTER TABLE gemini_users SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_users_history));
ALTER TABLE gemini_cardissuesequence SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_cardissuesequence_history));
ALTER TABLE gemini_projectattributes SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectattributes_history));
ALTER TABLE gemini_testing_run_times SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_run_times_history));
ALTER TABLE gemini_testing_history SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_history_history));
ALTER TABLE gemini_issuepriorities SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuepriorities_history));
ALTER TABLE gemini_projectgroupmembership SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectgroupmembership_history));
ALTER TABLE gemini_testing_plan_cases SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_plan_cases_history));
ALTER TABLE gemini_issueresources SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issueresources_history));
ALTER TABLE gemini_testing_customdata SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_customdata_history));
ALTER TABLE gemini_apppermissions SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_apppermissions_history));
ALTER TABLE gemini_webnode SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_webnode_history));
ALTER TABLE gemini_projectaudit SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectaudit_history));
ALTER TABLE gemini_webnodedata SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_webnodedata_history));
ALTER TABLE gemini_projectdocuments SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectdocuments_history));
ALTER TABLE gemini_projectdefaultvalues SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectdefaultvalues_history));
ALTER TABLE gemini_sla SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_sla_history));
ALTER TABLE gemini_issuecomponents SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuecomponents_history));
ALTER TABLE gemini_navigationcard SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_navigationcard_history));
ALTER TABLE gemini_customfielddata SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_customfielddata_history));
ALTER TABLE gemini_testing_case_steps SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_case_steps_history));
ALTER TABLE gemini_install SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_install_history));
ALTER TABLE gemini_testing_runs SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_runs_history));
ALTER TABLE gemini_projectlabels SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projectlabels_history));
ALTER TABLE gemini_applicationsettings SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_applicationsettings_history));
ALTER TABLE gemini_organization SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_organization_history));
ALTER TABLE gemini_organizationmembership SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_organizationmembership_history));
ALTER TABLE gemini_testing_attachments SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_attachments_history));
ALTER TABLE gemini_testing_case_issues SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_testing_case_issues_history));
ALTER TABLE gemini_sharedviews SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_sharedviews_history));
ALTER TABLE gemini_optoutemails SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_optoutemails_history));
ALTER TABLE gemini_issuetimetype SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuetimetype_history));
ALTER TABLE gemini_versions SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_versions_history));
ALTER TABLE gemini_issuetypes SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_issuetypes_history));
ALTER TABLE gemini_globalsecurityschemes SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_globalsecurityschemes_history));
ALTER TABLE gemini_templatedcontent SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_templatedcontent_history));
ALTER TABLE gemini_projects SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_projects_history));
ALTER TABLE gemini_components SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_components_history));
ALTER TABLE gemini_versionmilestone SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = {{schema}}.gemini_versionmilestone_history));
